version: 2

models:
  - name: dim_listings_cleansed
    columns:

     - name: listing_id
       tests:
         - unique
         - not_null
     - name: MINIMUM_NIGHTS
       tests:
         - positive_value
               

     - name: host_id
       tests:
         - not_null
         - relationships:
             to: ref('dim_hosts_cleansed')
             field: host_id

     - name: room_type
       tests:
         - accepted_values:
             values: ['Entire home/apt',
                      'Private room',
                      'Shared room',
                      'Hotel room']
        
  - name: dim_lisitngs_w_hosts

    tests:
      - dbt_expectations.expect_table_row_count_to_equal_other_table:
          compare_model: source ('airbnb','RAW_LISTINGS')

    columns:
      - name: price
        tests:  
          - dbt_expectations.expect_column_quantile_values_to_be_between:
              quantile: .99
              min_value: 50
              max_value: 500
          - dbt_expectations.expect_column_max_to_be_between:
              max_value: 5000
              config:
                severity: warn 