version: 2

sources:
  - name: airbnb
    schema: RAW
    tables:
      - name: RAW_LISTINGS


      - name: RAW_HOSTS
      - name: RAW_REVIEWS
      - name: raw_customer2
      - name: CUSTOMER
      - name: raw_customer
      - name: sales_us
